services:
  auth_service:
    build:
      context: ./auth_service
    ports:
      - "8001:8001"
    environment:
      - SECRET_KEY=supersecret

  mcp_gateway:
    build:
      context: ./mcp_gateway
    ports:
      - "8000:8000"
    depends_on:
      auth_service:
        condition: service_started
      office_security_service:
        condition: service_started
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GEMINI_MODEL=gemini-1.5-pro-latest
      - AUTH_URL=http://auth_service:8001/token/validate
      - AUTH_URL_BASE=http://auth_service:8001 # Add this if using the new env var
      - OFFICE_SECURITY_API_URL=http://office_security_service:8004
      - COMMITTEE_HEARING_API_URL=http://committee_hearing_security_service:8005
    volumes:
      - ./common:/app/common  # ✅ Mounts shared auth module

  leave_service:
    build:
      context: ./leave_service
    ports:
      - "8002:8002"
    depends_on:
      auth_service:
        condition: service_started
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY} # Pass your Google API key
      - GEMINI_MODEL=gemini-1.5-pro-latest    # Updated to a more advanced Pro model
      - AUTH_URL=http://auth_service:8001/token/validate # Keep this
    volumes:
      - ./common:/app/common  # ✅ Mounts shared auth module

  it_helpdesk_service:
    build:
      context: ./it_helpdesk_service
    ports:
      - "8003:8003"
    depends_on:
      auth_service:
        condition: service_started
    environment:
      - AUTH_URL=http://auth_service:8001/token/validate
    volumes:
      - ./common:/app/common  # ✅ Mounts shared auth module

  office_security_service:
    build:
      context: ./office_security_service
    ports:
      - "8004:8004"
    depends_on:
      auth_service:
        condition: service_started
    environment:
      - AUTH_URL=http://auth_service:8001/token/validate
      - EXTERNAL_SECURITY_API_BASE_URL=https://api-osepc-stage.apps.vep1.senate.gov/api/v1/


  committee_hearing_security_service:
    build:
      context: ./committee_hearing_security_service
    ports:
      - "8005:8005"
    depends_on:
      auth_service:
        condition: service_started
    environment:
      - AUTH_URL=http://auth_service:8001/token/validate

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - mcp_gateway